#
# Конфигурация основных параметров бота
#

# Настройка подключения к БД через Hibernate
# Версия драйвера H2 должен быть не выше 1.4.200
database:
  'hibernate.dialect': "org.hibernate.dialect.H2Dialect"
  'hibernate.connection.driver_class': "org.h2.Driver"
  'hibernate.connection.url': "jdbc:h2:./database;mode=MYSQL"
  'hibernate.connection.username': "user"
  'hibernate.connection.password': "user"
  'hibernate.show_sql': "false"
  'hibernate.hbm2ddl.auto': "create"
  'hibernate.jdbc.batch_size': "50"

# Настройка подключения к Telegram боту
telegram:
  bot_name: "VasyaSchedulerBot"
  token: "TOKEN"

# Настройка регулярных выражений для поиска необходимых подстрок в расписании
# Советуется изменять только, если вы придумали лучшее выражение, или формат указания ФИО изменился
regex:
  # Обычное представление ФИО преподавателя типа Фамилия И.О. или статус.Фамилия И.О.
  teacher_default: "([А-ЯЁЇІЄҐ][а-яёїієґ']{0,32})\\s*([А-ЯЁЇІЄҐ])\\.\\s*([А-ЯЁЇІЄҐ])\\.*"
  # Выражение для поиска ФИО преподавателя на одной строке с аудиторией типа 'Фамилия И.О. ауд.203, Ещефамилия В.В ауд.204'
  teacher_inline: "([А-ЯЁЇІЄҐ][а-яёїієґ']{1,32}\\s*[А-ЯЁЇІЄҐ]\\.\\s*[А-ЯЁЇІЄҐ]\\.*)\\s*(ауд\\..{1,3})"
  # Выражение для выделения номера аудитории
  classroom: "[а-яёїієґ']*\\.*\\s*([0-9]{3})"

# Настройка параметров для получения оценок
points:
  # Адрес сервера оценок
  url: "http://77.93.42.90:81/uspeh/index.php"
  # Данные для POST запроса на авторизацию
  login_query: "action=login&lastname=${lastname}&n1=${n1}&n2=${n2}&password=${password}&submit=%C2%EE%E9%F2%E8"
  # Код ответа, означающий успешную авторизацию
  login_success: 302
  # Макс. время жизни подключения в секундах
  timeout: 3

# Кол-во потоков для параллельной обработки запросов
thread_pool_size: 6

# Настройка REST API для панели управления
rest_api:
  # Запускать ли API сервер
  enable: false
  # Порт, на котором будет работать сервер
  port: 8080